### PR TITLE
Issue #419: Execute on change after making sure the state changed

### PR DESCRIPTION
**Pull request by bdweikat**
…ore the second character - excute on change after state changed

Fixes #ABC

What did you change (functionally and technically)?

**Checklist** (remove this list before you submit the PR)
* Are there tests for the new code?
* Does the code comply to our code conventions?
* Does the PR resolve the whole issue?

**Additional review hints** (remove this list before you submit the PR)
* Besides the code review, what should the reviewer test?
* Are there any edge cases?
* Do you have any test files or test set-up?
* Could your changes cause side effects elsewhere in the code base?

### CODE REVIEW

**Comment by bdweikat** [comment]
#419

**Comment by bdweikat** [comment]
@jfschwarz is there any chance to check this PR

**Comment by jfschwarz** [comment]
Hi @bdweikat. We're missing some documentation/explanation on why this change would make sense. The PR does not reference a bug ticket. Does it solve a problem for you? Which one? Optimally, you'd demonstrate the problem with a test case or a little example. Hard to assess this change otherwise... 🤷‍♂️

**Comment by bdweikat** [comment]
@jfschwarz here is the issue https://github.com/signavio/react-mentions/issues/419

**Comment by jfschwarz** [comment]
Ah yes, it's right there in the title 🤦
I'm checking it...

**Review by jfschwarz — CHANGES_REQUESTED** [review]
Unfortunately your change breaks typing with the cursor set somewhere other than the end of the value.

Sep-09-2020 12-21-14

**Comment by bdweikat** [comment]
@jfschwarz can you review it again please

**Comment by Sigrsig** [comment]
Fixed with [fix: Take newly typed characters into account when a mention is deleted](https://github.com/signavio/react-mentions/pull/565)

**Pull request closed without merging**
