### PR TITLE
refactor: SuggestionsOverlay.js functional component

### PR DESCRIPTION
**Pull request by Sigrsig**
Converts SuggestionsOverlay.js from class component to functional component

### CODE REVIEW

**Review by dev-talha-akbar — APPROVED** [review]
Flawless, @Sigrsig! 🚀

**Comment by Sigrsig** [comment]
> @Sigrsig One question, however: did someone forget to add `customSuggestionsContainer` to `propTypes` before and if yes, now it's there, do we have better prop type than `any`?

That's a good question. I guess it would depend on how the user would use it? If it's only React elements we could use `PropTypes.element`?

**Comment by dev-talha-akbar** [comment]
@Sigrsig Based on the code at line 67, could we use `PropTypes.func`?

**Comment by Sigrsig** [comment]
Sounds like a plan. I'll do a quick fix for that today!

**Pull request merged**
