### PR TITLE
chore: Remove lodash

### LINKED ISSUE #284: Consider removing lodash
When looking at https://bundlephobia.com/result?p=react-mentions@2.4.0, it seems like 59% of react-mentions package is lodash. There's is more lodash code than react-mentions itself.

Lodash has been a dependency since 0.3.0 (~ 2 years ago) and a lot has changed since.

I found 6 lodash functions being used: 

| Lodash  | Suggestions |
| ------------- | ------------- |
| omit  | var { a, b, ...result } = object;  |
| keys  | Object.keys  |
| isEqual  | hand written alternative using ===  |
| isNumber  | typeof value === 'number' |
| isFinite  | Number.isFinite  |
| values  | Object.values  |

There might be better alternatives, these are just suggestions.

Some of these are not cross-browser compatible, that is truth, but polyfills is very common (and expected) for apps that need to support other browsers. The rest operator is transpiled by Babel/TypeScript into valid ES5 code. We don't need to push all these lodash functions to browsers that have this built-in. 

Without lodash, this package could be reduced to ~40kB, that's a ~50% reduction.

Any thoughts?

### PR DESCRIPTION
**Pull request by matthewtmoran**
Fixes #284

Removed lodash dependency.  Replaced with simplified util functions.   Some of which were taken straight from @goenning 's PR.  Included tests.  Instead of using `_.values`, used `Object.values`.

### CODE REVIEW

**Comment by frontendphil** [comment]
Hey @matthewtmoran thanks for this PR. Could you rebase onto latest master?

**Comment by matthewtmoran** [comment]
> Hey @matthewtmoran thanks for this PR. Could you rebase onto latest master?

I'm not sure I did this correctly.

**Comment by matthewtmoran** [comment]
@frontendphil what do I need to do to get this merged in?

**Comment by krzysiek1507** [comment]
Any chance to merge it?

**Comment by krzysiek1507** [comment]
Thanks!

**Comment by krzysiek1507** [comment]
@jfschwarz any chance for a new version release?

**Pull request merged**
